name = "prime-analytics"
compatibility_date = "2026-07-23"
account_id = "334696cbcfac3868e5a054bb7771257d"

[assets]
directory = "./website"
not_found_handling = "404-page"

[[routes]]
pattern = "primeanalytics.ai"
custom_domain = true

[[routes]]
pattern = "www.primeanalytics.ai"
custom_domain = true
