name = "prime-analytics"
main = "worker.js"
compatibility_date = "2026-07-23"
account_id = "334696cbcfac3868e5a054bb7771257d"

[assets]
directory = "./website"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = true

[[routes]]
pattern = "primeanalytics.ai"
custom_domain = true

[[routes]]
pattern = "www.primeanalytics.ai"
custom_domain = true
